# ---------------------------------------------------------------------------#
# Helpers for the real-data tests of obwoe_select() and obwoe_sql()
#
# The SQL generated by obwoe_sql() is validated by parsing and evaluating it
# with a small, self-contained CASE interpreter defined below. Nothing outside
# base R is required: the interpreter reads the emitted text the way a database
# engine would, so a wrong predicate or a mis-escaped literal shows up as a
# wrong bin assignment rather than as a string comparison against the code that
# produced it.
# ---------------------------------------------------------------------------#

#' Load the bundled Statlog (German Credit) benchmark
#'
#' 1000 loan applications, 7 numerical and 13 categorical attributes. The
#' returned frame carries a `target` column coded 1 = bad (event), 0 = good,
#' the convention used throughout the package.
#'
#' @return A data.frame, or NULL when the file is not installed.
german_credit <- function() {
  path <- system.file("extdata", "germancredit.csv.gz",
    package = "OptimalBinningWoE"
  )
  if (!nzchar(path) || !file.exists(path)) {
    return(NULL)
  }
  con <- gzfile(path)
  on.exit(try(close(con), silent = TRUE), add = TRUE)
  df <- utils::read.csv(con, stringsAsFactors = FALSE)
  df$target <- as.integer(1L - df$credit_risk)
  df$credit_risk <- NULL
  df
}

#' Skip a test unless the German Credit benchmark is installed
skip_if_no_german <- function() {
  if (is.null(german_credit())) {
    testthat::skip("Bundled German Credit data not installed")
  }
}


# ---------------------------------------------------------------------------#
# Minimal SQL reader
# ---------------------------------------------------------------------------#

#' Split a SQL string-literal list into the values it denotes
#'
#' Understands the ANSI convention where an embedded single quote is written
#' twice. Handles `'a'`, `'a', 'b'` and literals containing commas or quotes.
#'
#' @param s Text holding one or more single-quoted literals.
#' @return A character vector of unquoted values.
sql_parse_strings <- function(s) {
  chars <- strsplit(s, "", fixed = TRUE)[[1L]]
  n <- length(chars)
  out <- character(0)
  cur <- NULL
  i <- 1L
  while (i <= n) {
    ch <- chars[i]
    if (is.null(cur)) {
      if (identical(ch, "'")) cur <- character(0)
      i <- i + 1L
    } else if (identical(ch, "'")) {
      if (i < n && identical(chars[i + 1L], "'")) {
        cur <- c(cur, "'")
        i <- i + 2L
      } else {
        out <- c(out, paste(cur, collapse = ""))
        cur <- NULL
        i <- i + 1L
      }
    } else {
      cur <- c(cur, ch)
      i <- i + 1L
    }
  }
  out
}

# ---------------------------------------------------------------------------#
# Exact decimal helpers
#
# Enough decimal arithmetic to name the double a literal denotes. Digit strings
# padded to a common shape compare and add exactly, and `sprintf()` hands the
# rendering to the C library, which is correctly rounded everywhere -- so none
# of this depends on how wide R's `LDOUBLE` happens to be.
# ---------------------------------------------------------------------------#

#' Pad plain non-negative decimals to a common shape and drop the point
#'
#' The results are equal-length digit strings, so comparing or adding them
#' digit by digit is comparing or adding the numbers they spell.
dec_align <- function(x) {
  ip <- sub("\\..*$", "", x)
  fp <- ifelse(grepl(".", x, fixed = TRUE), sub("^[^.]*\\.", "", x), "")
  paste0(
    strrep("0", max(nchar(ip)) - nchar(ip)), ip,
    fp, strrep("0", max(nchar(fp)) - nchar(fp))
  )
}

#' Compare two aligned digit strings: -1, 0 or 1
dec_cmp <- function(a, b) {
  d <- which(utf8ToInt(a) != utf8ToInt(b))
  if (length(d) == 0L) {
    0L
  } else if (utf8ToInt(a)[d[1L]] < utf8ToInt(b)[d[1L]]) {
    -1L
  } else {
    1L
  }
}

#' Add two aligned digit strings, carrying into one extra leading digit
dec_add <- function(a, b) {
  s <- rev((utf8ToInt(a) - 48L) + (utf8ToInt(b) - 48L))
  carry <- 0L
  for (i in seq_along(s)) {
    tot <- s[i] + carry
    s[i] <- tot %% 10L
    carry <- tot %/% 10L
  }
  paste(c(carry, rev(s)), collapse = "")
}

#' The exact decimal expansion of a positive double
#'
#' A double is `m * 2^e`, so its expansion terminates after `-e` decimals and
#' `sprintf()` prints it in full rather than rounding it.
dec_exact <- function(x) {
  nd <- pmin(1074L, pmax(0L, 53L - as.integer(floor(log2(x)))))
  vapply(seq_along(x), function(i) sprintf("%.*f", nd[i], x[i]),
    character(1L)
  )
}


#' Read a generated numeric literal back to the double it denotes
#'
#' `as.numeric()` accumulates the digits of a decimal string in `LDOUBLE`,
#' which is no wider than a `double` where R is built without long double
#' support (CRAN's noLD flavour) and on aarch64 macOS. A literal spelling out
#' all 17 significant digits can then come back a few ULP from the double it
#' names, and a probe sitting exactly on a cut point is pushed into the next
#' bin -- a failure of R's string-to-double conversion, not of the SQL the
#' package wrote. A database reads the literal correctly, so this evaluator
#' has to as well, or it is not emulating one.
#'
#' Three routes, none of which trusts `as.numeric()` with a literal it cannot
#' be shown to parse exactly:
#'
#' * Digits below 2^53 and at most 22 decimals: the value is `m / 10^nd`, one
#'   correctly rounded division of two exactly representable doubles.
#' * Otherwise, when the literal carries more digits than are needed to
#'   separate two doubles, exactly one double prints back as the literal, so
#'   `as.numeric()`'s answer is accepted once `sprintf()` confirms it.
#' * Otherwise the neighbouring doubles are bracketed around the literal by
#'   exact decimal comparison and the nearer of the two wins, deciding the
#'   midpoint as `2*lit` against `a + b` so that no inexact subtraction enters.
#'
#' @param lit Character literals, as they appear in the generated SQL.
#' @return The doubles they denote; `NA` for `NULL` and for anything that is
#'   not a plain decimal.
sql_read_number <- function(lit) {
  lit <- as.character(lit)
  key <- unique(lit)
  val <- vapply(key, sql_read_number1, numeric(1L), USE.NAMES = FALSE)
  val[match(lit, key)]
}

sql_read_number1 <- function(s) {
  s <- trimws(s)
  z <- suppressWarnings(as.numeric(s))
  # Only a plain decimal is decoded here. Scientific notation, NULL and
  # non-numbers are left to as.numeric().
  if (is.na(z) || !is.finite(z) || z == 0 ||
    !grepl("^-?[0-9]+(\\.[0-9]+)?$", s)) {
    return(z)
  }
  neg <- startsWith(s, "-")
  if (neg) s <- substring(s, 2L)
  dot <- regexpr(".", s, fixed = TRUE)
  nd <- if (dot < 0L) 0L else nchar(s) - dot
  sgn <- if (neg) -1 else 1

  m <- as.numeric(gsub(".", "", s, fixed = TRUE))
  if (m < 9007199254740992 && nd <= 22L) {
    return(sgn * (m / 10^nd))
  }

  z <- abs(z)
  u <- 2^(floor(log2(z)) - 52L)
  if (nd * log(10) > -log(u) && identical(sprintf("%.*f", nd, z), s)) {
    return(sgn * z)
  }

  # Every double within a few ULP of R's reading, walked in half steps too so
  # that the finer grid below a power of two is covered as well.
  off <- c(-64:-1, 1:64)
  cand <- sort(unique(c(z, z + off * u, z + off * (u / 2))))
  cand <- cand[cand > 0]
  pad <- dec_align(c(s, dec_exact(cand)))
  ord <- vapply(pad[-1L], dec_cmp, integer(1L), b = pad[1L], USE.NAMES = FALSE)
  if (any(ord == 0L)) {
    return(sgn * cand[which(ord == 0L)[1L]])
  }
  lo <- which(ord < 0L)
  hi <- which(ord > 0L)
  if (length(lo) == 0L || length(hi) == 0L) {
    return(sgn * z) # literal outside the window; nothing better to offer
  }
  a <- max(lo)
  b <- min(hi)
  # Nearer of the two, i.e. which side of (a + b)/2 the literal falls on.
  two <- dec_align(c(dec_add(pad[1L], pad[1L]), dec_add(pad[a + 1L], pad[b + 1L])))
  side <- dec_cmp(two[1L], two[2L])
  if (side == 0L) {
    # Exactly halfway: to even, as IEEE 754 rounds.
    side <- if ((cand[a] / u) %% 2 == 0) -1L else 1L
  }
  sgn * if (side < 0L) cand[a] else cand[b]
}


#' Evaluate a single SQL predicate against a column of values
#'
#' @param pred The predicate text, e.g. `x > 7 AND x <= 10`.
#' @param values The column values.
#' @param col The unquoted column name the predicate refers to.
#' @return A logical vector; SQL three-valued logic collapses to FALSE, which
#'   is exactly how a CASE branch behaves.
sql_eval_predicate <- function(pred, values, col) {
  pred <- trimws(pred)

  # Escape every non-word character so the column name is matched literally
  esc <- gsub("([^A-Za-z0-9_])", "\\\\\\1", col)
  colpat <- paste0("^(?:", esc, "|\"", esc, "\"|`", esc, "`|\\[", esc, "\\])\\s*")
  strip_col <- function(x) sub(colpat, "", trimws(x), perl = TRUE)

  rest <- strip_col(pred)

  if (identical(rest, "IS NULL")) {
    return(is.na(values))
  }

  if (startsWith(rest, "IN (")) {
    inside <- sub("^IN \\((.*)\\)$", "\\1", rest)
    wanted <- sql_parse_strings(inside)
    return(!is.na(values) & as.character(values) %in% wanted)
  }

  if (startsWith(rest, "= '")) {
    wanted <- sql_parse_strings(sub("^= ", "", rest))
    return(!is.na(values) & as.character(values) == wanted[1L])
  }

  # Numeric comparison, possibly two bounds joined by AND
  atoms <- strsplit(rest, " AND ", fixed = TRUE)[[1L]]
  v <- suppressWarnings(as.numeric(values))
  res <- rep(TRUE, length(values))
  for (a in atoms) {
    a <- strip_col(a)
    op <- regmatches(a, regexpr("^(<=|>=|<>|<|>|=)", a))
    if (length(op) != 1L) stop("unparseable predicate in generated SQL: ", pred)
    lit <- sql_read_number(sub("^(<=|>=|<>|<|>|=)", "", a))
    cmp <- switch(op,
      "<=" = v <= lit,
      ">=" = v >= lit,
      "<" = v < lit,
      ">" = v > lit,
      "=" = v == lit,
      "<>" = v != lit
    )
    cmp[is.na(cmp)] <- FALSE
    res <- res & cmp
  }
  res
}


#' Evaluate a generated CASE expression
#'
#' Applies the branches top to bottom exactly as SQL does: the first matching
#' WHEN wins, ELSE catches the rest.
#'
#' @param case_sql The CASE expression text.
#' @param values The column values it refers to.
#' @param col The unquoted column name.
#' @return A character vector of the THEN literals that fired, unparsed.
sql_eval_case <- function(case_sql, values, col) {
  lines <- trimws(strsplit(as.character(case_sql), "\n", fixed = TRUE)[[1L]])
  out <- rep(NA_character_, length(values))
  done <- rep(FALSE, length(values))

  for (ln in lines) {
    if (startsWith(ln, "WHEN ")) {
      m <- regmatches(ln, regexec("^WHEN (.*) THEN (.*)$", ln))[[1L]]
      if (length(m) != 3L) stop("unparseable WHEN branch: ", ln)
      hit <- sql_eval_predicate(m[2L], values, col)
      fire <- !done & hit
      out[fire] <- m[3L]
      done <- done | fire
    } else if (startsWith(ln, "ELSE ")) {
      val <- sub("^ELSE ", "", ln)
      out[!done] <- val
      done[] <- TRUE
    }
  }
  out
}

#' Evaluate a CASE expression and decode the results as numbers
sql_eval_case_num <- function(case_sql, values, col) {
  lit <- sql_eval_case(case_sql, values, col)
  sql_read_number(lit)
}

#' Evaluate a CASE expression and decode the results as strings
sql_eval_case_str <- function(case_sql, values, col) {
  lit <- sql_eval_case(case_sql, values, col)
  vapply(lit, function(x) {
    if (is.na(x) || identical(x, "NULL")) {
      return(NA_character_)
    }
    v <- sql_parse_strings(x)
    if (length(v) == 0L) NA_character_ else v[1L]
  }, character(1), USE.NAMES = FALSE)
}

#' Tolerance for a comparison that reads a generated literal back with as.numeric()
#'
#' R accumulates the decimal digits of a string in `LDOUBLE`, which on aarch64
#' macOS is no wider than a `double`. There `as.numeric()` can land one bit from
#' the nearest double for a literal carrying more than fifteen digits, so a
#' bit-exact comparison would be testing R's own string-to-double conversion
#' rather than the SQL the package generated. The probe below detects that and
#' relaxes those comparisons to a few ULP; everywhere else -- Linux, Windows,
#' macOS on x86_64 -- they stay exact.
#'
#' @return `0` where R parses exactly, a small tolerance where it does not.
sql_read_tolerance <- function() {
  set.seed(20260825)
  probe <- c(
    rnorm(200), 0.43675438268898403, -0.16634225323308749,
    0.73219048278227306, -0.36497312083599037
  )
  if (all(as.numeric(sprintf("%.17g", probe)) == probe)) 0 else 1e-14
}


#' Spell out a disagreement between SQL-evaluated WoE and R-applied WoE
#'
#' waldo cannot diff two doubles that print alike, so a one-bit disagreement
#' reports only "actual != expected but don't know how to show the difference",
#' which says nothing about where it came from. This renders the offending row
#' at full precision along with the literals the CASE offers, so a failure on a
#' machine we cannot reach is still diagnosable from the check artifact.
#'
#' @param feature Feature name, used as the label when nothing differs.
#' @param case_sql The generated CASE expression.
#' @param got WoE obtained by evaluating the SQL.
#' @param ref WoE obtained from `obwoe_apply()`.
#'
#' @return A character scalar for `expect_equal(info = )`.
sql_woe_mismatch <- function(feature, case_sql, got, ref) {
  if (identical(got, ref)) {
    return(feature)
  }
  differs <- !vapply(
    seq_along(got), function(j) identical(got[j], ref[j]), logical(1)
  )
  if (!any(differs)) {
    return(feature)
  }
  j <- which(differs)[1L]
  lines <- trimws(strsplit(as.character(case_sql), "\n", fixed = TRUE)[[1L]])
  thens <- sub("^.*THEN ", "", grep(" THEN ", lines, fixed = TRUE, value = TRUE))
  sprintf(
    "%s: %d of %d rows differ; row %d sql=%.17g apply=%.17g; THEN literals: %s",
    feature, sum(differs), length(got), j, got[j], ref[j],
    paste(utils::head(unique(thens), 12L), collapse = " ")
  )
}


#' Bin labels compare equal ignoring R's declared encoding
#'
#' Bin labels come back from the C++ layer as byte strings with no encoding
#' mark; comparing the bytes avoids spurious mismatches on non-ASCII data.
same_labels <- function(a, b) {
  identical(enc2utf8(as.character(a)), enc2utf8(as.character(b)))
}

#' Ground truth: applying the generated SQL to the training data must
#' reproduce the algorithm's own bin counts
#'
#' The comparison is against the counts the binning algorithm itself reported,
#' not against another R implementation, so a wrong interval boundary in the
#' generated SQL cannot hide behind a matching bug elsewhere.
#'
#' @param model An `obwoe` object.
#' @param data The training data.
#' @param features Features to verify.
#' @param check_class Also verify the event/non-event split per bin.
#' @param ... Passed to `obwoe_sql()`.
#'
#' @return A character vector of failure messages (empty when all match).
sql_reproduces_bin_counts <- function(model, data, features,
                                      check_class = TRUE, ...) {
  target <- model$target
  cases <- obwoe_sql(model,
    features = features, output = "bin", style = "case",
    comment = FALSE, quote_identifiers = "never", ...
  )

  problems <- character(0)
  for (f in features) {
    alias <- paste0(f, "_bin")
    if (!alias %in% names(cases)) next
    res <- model$results[[f]]
    if (!is.null(res$error)) next

    assigned <- sql_eval_case_str(cases[[alias]], data[[f]], f)
    lev <- enc2utf8(as.character(res$bin))
    got <- factor(enc2utf8(assigned), levels = lev)

    if (anyNA(got)) {
      problems <- c(problems, sprintf(
        "%s: %d rows were not assigned to any fitted bin", f, sum(is.na(got))
      ))
      next
    }
    if (!identical(as.integer(table(got)), as.integer(res$count))) {
      problems <- c(problems, sprintf("%s: bin counts differ", f))
      next
    }
    if (check_class) {
      y <- data[[target]]
      p <- as.integer(table(factor(got[y == 1], levels = lev)))
      n <- as.integer(table(factor(got[y == 0], levels = lev)))
      if (!identical(p, as.integer(res$count_pos)) ||
        !identical(n, as.integer(res$count_neg))) {
        problems <- c(problems, sprintf("%s: event/non-event split differs", f))
      }
    }
  }
  problems
}
