# ---------------------------------------------------------------------------#
# Helpers for the real-data tests of obwoe_select() and obwoe_sql()
#
# The SQL generated by obwoe_sql() is validated by parsing and evaluating it
# with a small, self-contained CASE interpreter defined below. Nothing outside
# base R is required: the interpreter reads the emitted text the way a database
# engine would, so a wrong predicate or a mis-escaped literal shows up as a
# wrong bin assignment rather than as a string comparison against the code that
# produced it.
# ---------------------------------------------------------------------------#

#' Load the bundled Statlog (German Credit) benchmark
#'
#' 1000 loan applications, 7 numerical and 13 categorical attributes. The
#' returned frame carries a `target` column coded 1 = bad (event), 0 = good,
#' the convention used throughout the package.
#'
#' @return A data.frame, or NULL when the file is not installed.
german_credit <- function() {
  path <- system.file("extdata", "germancredit.csv.gz",
    package = "OptimalBinningWoE"
  )
  if (!nzchar(path) || !file.exists(path)) {
    return(NULL)
  }
  con <- gzfile(path)
  on.exit(try(close(con), silent = TRUE), add = TRUE)
  df <- utils::read.csv(con, stringsAsFactors = FALSE)
  df$target <- as.integer(1L - df$credit_risk)
  df$credit_risk <- NULL
  df
}

#' Skip a test unless the German Credit benchmark is installed
skip_if_no_german <- function() {
  if (is.null(german_credit())) {
    testthat::skip("Bundled German Credit data not installed")
  }
}


# ---------------------------------------------------------------------------#
# Minimal SQL reader
# ---------------------------------------------------------------------------#

#' Split a SQL string-literal list into the values it denotes
#'
#' Understands the ANSI convention where an embedded single quote is written
#' twice. Handles `'a'`, `'a', 'b'` and literals containing commas or quotes.
#'
#' @param s Text holding one or more single-quoted literals.
#' @return A character vector of unquoted values.
sql_parse_strings <- function(s) {
  chars <- strsplit(s, "", fixed = TRUE)[[1L]]
  n <- length(chars)
  out <- character(0)
  cur <- NULL
  i <- 1L
  while (i <= n) {
    ch <- chars[i]
    if (is.null(cur)) {
      if (identical(ch, "'")) cur <- character(0)
      i <- i + 1L
    } else if (identical(ch, "'")) {
      if (i < n && identical(chars[i + 1L], "'")) {
        cur <- c(cur, "'")
        i <- i + 2L
      } else {
        out <- c(out, paste(cur, collapse = ""))
        cur <- NULL
        i <- i + 1L
      }
    } else {
      cur <- c(cur, ch)
      i <- i + 1L
    }
  }
  out
}

#' Evaluate a single SQL predicate against a column of values
#'
#' @param pred The predicate text, e.g. `x > 7 AND x <= 10`.
#' @param values The column values.
#' @param col The unquoted column name the predicate refers to.
#' @return A logical vector; SQL three-valued logic collapses to FALSE, which
#'   is exactly how a CASE branch behaves.
sql_eval_predicate <- function(pred, values, col) {
  pred <- trimws(pred)

  # Escape every non-word character so the column name is matched literally
  esc <- gsub("([^A-Za-z0-9_])", "\\\\\\1", col)
  colpat <- paste0("^(?:", esc, "|\"", esc, "\"|`", esc, "`|\\[", esc, "\\])\\s*")
  strip_col <- function(x) sub(colpat, "", trimws(x), perl = TRUE)

  rest <- strip_col(pred)

  if (identical(rest, "IS NULL")) {
    return(is.na(values))
  }

  if (startsWith(rest, "IN (")) {
    inside <- sub("^IN \\((.*)\\)$", "\\1", rest)
    wanted <- sql_parse_strings(inside)
    return(!is.na(values) & as.character(values) %in% wanted)
  }

  if (startsWith(rest, "= '")) {
    wanted <- sql_parse_strings(sub("^= ", "", rest))
    return(!is.na(values) & as.character(values) == wanted[1L])
  }

  # Numeric comparison, possibly two bounds joined by AND
  atoms <- strsplit(rest, " AND ", fixed = TRUE)[[1L]]
  v <- suppressWarnings(as.numeric(values))
  res <- rep(TRUE, length(values))
  for (a in atoms) {
    a <- strip_col(a)
    op <- regmatches(a, regexpr("^(<=|>=|<>|<|>|=)", a))
    if (length(op) != 1L) stop("unparseable predicate in generated SQL: ", pred)
    lit <- as.numeric(trimws(sub("^(<=|>=|<>|<|>|=)", "", a)))
    cmp <- switch(op,
      "<=" = v <= lit,
      ">=" = v >= lit,
      "<" = v < lit,
      ">" = v > lit,
      "=" = v == lit,
      "<>" = v != lit
    )
    cmp[is.na(cmp)] <- FALSE
    res <- res & cmp
  }
  res
}


#' Evaluate a generated CASE expression
#'
#' Applies the branches top to bottom exactly as SQL does: the first matching
#' WHEN wins, ELSE catches the rest.
#'
#' @param case_sql The CASE expression text.
#' @param values The column values it refers to.
#' @param col The unquoted column name.
#' @return A character vector of the THEN literals that fired, unparsed.
sql_eval_case <- function(case_sql, values, col) {
  lines <- trimws(strsplit(as.character(case_sql), "\n", fixed = TRUE)[[1L]])
  out <- rep(NA_character_, length(values))
  done <- rep(FALSE, length(values))

  for (ln in lines) {
    if (startsWith(ln, "WHEN ")) {
      m <- regmatches(ln, regexec("^WHEN (.*) THEN (.*)$", ln))[[1L]]
      if (length(m) != 3L) stop("unparseable WHEN branch: ", ln)
      hit <- sql_eval_predicate(m[2L], values, col)
      fire <- !done & hit
      out[fire] <- m[3L]
      done <- done | fire
    } else if (startsWith(ln, "ELSE ")) {
      val <- sub("^ELSE ", "", ln)
      out[!done] <- val
      done[] <- TRUE
    }
  }
  out
}

#' Evaluate a CASE expression and decode the results as numbers
sql_eval_case_num <- function(case_sql, values, col) {
  lit <- sql_eval_case(case_sql, values, col)
  suppressWarnings(as.numeric(lit))
}

#' Evaluate a CASE expression and decode the results as strings
sql_eval_case_str <- function(case_sql, values, col) {
  lit <- sql_eval_case(case_sql, values, col)
  vapply(lit, function(x) {
    if (is.na(x) || identical(x, "NULL")) {
      return(NA_character_)
    }
    v <- sql_parse_strings(x)
    if (length(v) == 0L) NA_character_ else v[1L]
  }, character(1), USE.NAMES = FALSE)
}

#' Bin labels compare equal ignoring R's declared encoding
#'
#' Bin labels come back from the C++ layer as byte strings with no encoding
#' mark; comparing the bytes avoids spurious mismatches on non-ASCII data.
same_labels <- function(a, b) {
  identical(enc2utf8(as.character(a)), enc2utf8(as.character(b)))
}

#' Ground truth: applying the generated SQL to the training data must
#' reproduce the algorithm's own bin counts
#'
#' The comparison is against the counts the binning algorithm itself reported,
#' not against another R implementation, so a wrong interval boundary in the
#' generated SQL cannot hide behind a matching bug elsewhere.
#'
#' @param model An `obwoe` object.
#' @param data The training data.
#' @param features Features to verify.
#' @param check_class Also verify the event/non-event split per bin.
#' @param ... Passed to `obwoe_sql()`.
#'
#' @return A character vector of failure messages (empty when all match).
sql_reproduces_bin_counts <- function(model, data, features,
                                      check_class = TRUE, ...) {
  target <- model$target
  cases <- obwoe_sql(model,
    features = features, output = "bin", style = "case",
    comment = FALSE, quote_identifiers = "never", ...
  )

  problems <- character(0)
  for (f in features) {
    alias <- paste0(f, "_bin")
    if (!alias %in% names(cases)) next
    res <- model$results[[f]]
    if (!is.null(res$error)) next

    assigned <- sql_eval_case_str(cases[[alias]], data[[f]], f)
    lev <- enc2utf8(as.character(res$bin))
    got <- factor(enc2utf8(assigned), levels = lev)

    if (anyNA(got)) {
      problems <- c(problems, sprintf(
        "%s: %d rows were not assigned to any fitted bin", f, sum(is.na(got))
      ))
      next
    }
    if (!identical(as.integer(table(got)), as.integer(res$count))) {
      problems <- c(problems, sprintf("%s: bin counts differ", f))
      next
    }
    if (check_class) {
      y <- data[[target]]
      p <- as.integer(table(factor(got[y == 1], levels = lev)))
      n <- as.integer(table(factor(got[y == 0], levels = lev)))
      if (!identical(p, as.integer(res$count_pos)) ||
        !identical(n, as.integer(res$count_neg))) {
        problems <- c(problems, sprintf("%s: event/non-event split differs", f))
      }
    }
  }
  problems
}
