#' @title Apply Optimal Weight of Evidence (WoE) to a Categorical Feature
#'
#' @description
#' Transforms a categorical feature into its corresponding Weight of Evidence (WoE)
#' values using pre-computed binning results from an optimal binning algorithm
#' (e.g., \code{\link{ob_categorical_cm}}).
#'
#' @param obresults List output from an optimal binning function for categorical
#'   variables. Must contain elements \code{bin} (character vector of bin labels)
#'   and \code{woe} (numeric vector of WoE values). Bins may represent individual
#'   categories or merged groups separated by \code{bin_separator}.
#' @param feature Character or factor vector of categorical values to be transformed.
#'   Automatically coerced to character if provided as factor.
#' @param bin_separator Character string used to separate multiple categories
#'   within a single bin label (default: \code{"\%;\%"}). For example, a bin
#'   \code{"A\%;\%B\%;\%C"} contains categories A, B, and C.
#' @param missing_values Character vector specifying which values should be treated
#'   as missing (default: \code{c("NA", "Missing", "")}). \code{NA} inputs and
#'   these values (after trimming surrounding whitespace) are scored with the
#'   missing-value bin: the first bin of \code{obresults} whose categories include
#'   one of them (the categorical binners store \code{NA} as the category
#'   \code{"NA"}), which is also the bin \code{\link{obwoe_sql}} and
#'   \code{\link{obwoe_apply}} use for missing values. A value that is itself a
#'   category of a bin (e.g. \code{"NA"}) is scored with that bin. Without a
#'   missing-value bin they are scored as \code{"Special"} with WoE \code{NA}.
#'
#' @return A data frame with one row per element of \code{feature} and the
#'   columns \code{feature} (the input), \code{bin} (the label of the matched
#'   bin, or \code{"Special"}), \code{woe} (the bin's WoE; \code{NA} for
#'   \code{"Special"}), \code{idbin} (the bin's \code{id}; the number of bins
#'   plus one for \code{"Special"}) and \code{ismissing} (1 for missing values
#'   and for categories not seen in \code{obresults}, 0 otherwise). Unseen
#'   categories are scored as \code{"Special"} without a warning.
#'
#' @details
#' This function is typically used in a two-step workflow:
#' \enumerate{
#'   \item Train binning on training data: \code{bins <- ob_categorical_cm(feature_train, target_train)}
#'   \item Apply WoE to new data: \code{woe_test <- ob_apply_woe_cat(bins, feature_test)}
#' }
#'
#' Bin labels are split on \code{bin_separator} and each value of
#' \code{feature} is matched against the resulting categories exactly, byte for
#' byte, as \code{\link{obwoe_apply}} and \code{\link{obwoe_sql}} do. A category
#' that appears in more than one bin label is scored with the first of those
#' bins, as in the \code{CASE} expression generated by \code{\link{obwoe_sql}}.
#' A value that only matches once leading and trailing whitespace is removed is
#' still accepted, and a category whose own name contains \code{bin_separator}
#' is recognised as a run of consecutive components of a bin label. Each
#' distinct value is resolved once, so scoring takes \eqn{O(n)} hash lookups
#' whatever the number of categories.
#'
#' @examples
#' \donttest{
#' # Mock data
#' train_data <- data.frame(
#'   category = c("A", "B", "A", "C", "B", "A"),
#'   default = c(0, 1, 0, 1, 0, 0)
#' )
#' test_data <- data.frame(
#'   category = c("A", "C", "B")
#' )
#'
#' # Train binning on training set
#' train_bins <- ob_categorical_cm(
#'   feature = train_data$category,
#'   target = train_data$default
#' )
#'
#' # Apply to test set
#' test_woe <- ob_apply_woe_cat(
#'   obresults = train_bins,
#'   feature = test_data$category
#' )
#'
#' # Handle custom missing indicators
#' test_woe <- ob_apply_woe_cat(
#'   obresults = train_bins,
#'   feature = test_data$category,
#'   missing_values = c("NA", "Unknown", "N/A", "")
#' )
#' }
#'
#' @export
ob_apply_woe_cat <- function(obresults,
                             feature,
                             bin_separator = "%;%",
                             missing_values = c("NA", "Missing", "")) {
  if (!is.list(obresults)) {
    stop("obresults must be a list (output from an optimal binning function).")
  }

  if (!all(c("bin", "woe") %in% names(obresults))) {
    stop("obresults must contain 'bin' and 'woe' elements.")
  }

  if (!is.character(feature)) {
    feature <- as.character(feature)
  }

  if (!is.character(bin_separator) || length(bin_separator) != 1) {
    stop("bin_separator must be a single character string.")
  }

  if (!is.character(missing_values)) {
    stop("missing_values must be a character vector.")
  }

  .Call(
    "_OptimalBinningWoE_OBApplyWoECat",
    obresults,
    feature,
    bin_separator,
    missing_values,
    PACKAGE = "OptimalBinningWoE"
  )
}
