# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimal_binning_categorical_cart <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_cart`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_cm <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_cm`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_dplc <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_dplc`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_fetb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_fetb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_gab <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L, population_size = 100L, num_generations = 100L, mutation_rate = 0.1, crossover_rate = 0.8, time_limit_seconds = 300L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_gab`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins, population_size, num_generations, mutation_rate, crossover_rate, time_limit_seconds)
}

optimal_binning_categorical_gmb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_gmb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_ivb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_ivb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_ldb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_ldb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_mba <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_mba`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_mblp <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_mblp`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_milp <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_milp`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_mob <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_mob`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_obnp <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_obnp`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_oslp <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L, monotonic = TRUE) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_oslp`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins, monotonic)
}

optimal_binning_categorical_sab <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L, initial_temperature = 1.0, cooling_rate = 0.995, max_iterations = 1000L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_sab`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins, initial_temperature, cooling_rate, max_iterations)
}

optimal_binning_categorical_sblp <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_sblp`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_swb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_swb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_categorical_udt <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_categorical_udt`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_bb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L, is_monotonic = TRUE) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_bb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins, is_monotonic)
}

optimal_binning_numerical_bs <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_bs`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_cart <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L, is_monotonic = TRUE) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_cart`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins, is_monotonic)
}

optimal_binning_numerical_cm <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_cm`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_dpb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L, n_threads = 1L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_dpb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins, n_threads)
}

optimal_binning_numerical_dplc <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_dplc`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_eb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L, n_threads = 1L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_eb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins, n_threads)
}

optimal_binning_numerical_eblc <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_eblc`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_efb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_efb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_ewb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_ewb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_fetb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_fetb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_gab <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_gab`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_gmb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_gmb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_ir <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_ir`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_ivb <- function(target, feature, min_bins = 3L, max_bins = 5L, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_ivb`, target, feature, min_bins, max_bins, max_n_prebins)
}

optimal_binning_numerical_jnbo <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_jnbo`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_kmb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_kmb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_ldb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_ldb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_lpdb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_lpdb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_mba <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L, n_threads = 1L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_mba`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins, n_threads)
}

optimal_binning_numerical_mblp <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_mblp`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_mdlp <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_mdlp`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_milp <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L, n_threads = 1L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_milp`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins, n_threads)
}

optimal_binning_numerical_mob <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_mob`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_obnp <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_obnp`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_oslp <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_oslp`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_plaob <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_plaob`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_qb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_qb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_sab <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_sab`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_sbb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_sbb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_mrblp <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L, n_threads = 1L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_mrblp`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins, n_threads)
}

optimal_binning_numerical_swb <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_swb`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_ubsd <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_ubsd`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

optimal_binning_numerical_udt <- function(target, feature, min_bins = 3L, max_bins = 5L, bin_cutoff = 0.05, max_n_prebins = 20L) {
    .Call(`_OptimalBinningWoE_optimal_binning_numerical_udt`, target, feature, min_bins, max_bins, bin_cutoff, max_n_prebins)
}

